WIP FB8-68: Introducing Transaction_seconds and a new I_S table Transacti…
facebook/mysql-5.6 pull request #1002
Opened 2019-03-27 07:45 UTC by dutow

…on_list

Jira ticket: https://jira.percona.com/browse/FB8-68

Reference commit: https://github.com/facebook/mysql-5.6/commit/73bb42f
Reference commit: https://github.com/facebook/mysql-5.6/commit/64b3247
Reference commit: https://github.com/facebook/mysql-5.6/commit/bd2054e

-------- 73bb42f --------

This patch adds two new time measurement stats for transactions:
- **Transaction_seconds**: the accumulated time the server spends to execute
  all commands in the current transaction. The transaction_seconds doesn't
  include client round trip time or replication delays. Measured in seconds.
- **Statement_seconds**: the time server spends to execute a single statement.
  Measured in seconds.
- Both time measurements will also reflect the time the server spends on the
  current running query.
- Both status can be viewed via `SHOW STATUS LIKE ...`.

As comparison, the existing `Command_seconds` is the accumulation of all
commands in a **session**. As the other time measurements, `Command_seconds`
will also reflect the time of the currently running query.

The following relationship of the three time stats always holds:
`Statement_seconds <= Transaction_seconds <= Command_seconds`

All of the three stats are now exposed in a new Information_Schema table
`Transaction_list`, which, similar to processlist, lists the above three time
stats for all current transactions. Table schema is described as below:

  +---------------------+---------------------+------+-----+----------+-------+
  | Field               | Type                | Null | Key | Default  | Extra |
  +---------------------+---------------------+------+-----+----------+-------+
  | ID                  | bigint(21) unsigned | NO   |     | 0        |       |
  | USER                | varchar(80)         | NO   |     |          |       |
  | HOST                | varchar(64)         | NO   |     |          |       |
  | DB                  | varchar(64)         | YES  |     | NULL     |       |
  | COMMAND             | varchar(16)         | NO   |     |          |       |
  | STATE               | varchar(64)         | YES  |     | NULL     |       |
  | STATEMENT_SECONDS   | decimal(9,6)        | NO   |     | 0.000000 |       |
  | TRANSACTION_SECONDS | decimal(9,6)        | NO   |     | 0.000000 |       |
  | COMMAND_SECONDS     | decimal(9,6)        | NO   |     | 0.000000 |       |
  | READ_ONLY           | tinyint(1) unsigned | NO   |     | 0        |       |
  | SQL_LOG_BIN         | tinyint(1) unsigned | NO   |     | 0        |       |
  +---------------------+---------------------+------+-----+----------+-------+

`READ_ONLY` field indicates whether the transaction have any writes, and
`SQL_LOG_BIN` field indicates if replication is turned on.

Note, all stats and the new I_S table are storage agnostic - They will work for
both Innodb and MyRocks.

2019-03-27 07:57 UTC, laurynas-biveinis requested changes

2019-03-27 07:57 UTC, laurynas-biveinis commented on include/mysql/components/services/psi_transaction_bits.h
> +typedef void (*set_transaction_time_v1_t)(struct PSI_transaction_locker *locker,
Prefer using in C++11

2019-03-27 07:57 UTC, laurynas-biveinis commented on include/mysql/psi/psi_abi_transaction_v1.h
> +
clang-format?

2019-03-27 07:57 UTC, laurynas-biveinis commented on mysql-test/t/show_transaction_list.test
> +
--source include/count_sessions.inc

2019-03-27 07:57 UTC, laurynas-biveinis commented on mysql-test/t/show_transaction_list.test
> +# For an open transation, Transaction_seconds should not be zero
This and all if/--die snippets below reinvent assert.inc, just use that instead

2019-03-27 07:57 UTC, laurynas-biveinis commented on mysql-test/t/show_transaction_list.test
> +drop table t1;
--source include/wait_until_count_sessions.inc

2019-03-27 07:57 UTC, laurynas-biveinis commented on sql/sp_instr.cc
> +But SP uses mysql_execute_command (which is used by the conventional
Why reformatted?

2019-03-27 07:57 UTC, laurynas-biveinis commented on sql/sql_class.h
> +
Why?

2019-03-27 07:57 UTC, laurynas-biveinis commented on sql/sql_parse.cc
> +      /*if (!thd->m_security_ctx->priv_user[0] &&
Why commented out code?

2019-03-27 07:57 UTC, laurynas-biveinis commented on sql/sql_show.cc
> +typedef std::tuple<double, double, double> time_stat_tuple;
Since it's "double, double, double", it is not clear which field means what, please consider a struct with three double fields instead

2019-03-27 07:57 UTC, laurynas-biveinis commented on storage/perfschema/pfs.cc
> +  DBUG_ASSERT(state != NULL);
s/NULL/nullptr/g

2019-03-27 20:41 UTC, percona-ysorokin requested changes

2019-03-27 20:41 UTC, percona-ysorokin commented on mysql-test/t/show_transaction_list.test
> +show processlist;
I believe `show processlist;` also needs masking at least for connection_id column

2019-03-27 20:41 UTC, percona-ysorokin commented on sql/log_event.cc
> +        mysql_parse(thd, &parser_state, &last_timer, true);
Why not just
```c++
ulonglong last_timer = my_timer_now();
mysql_parse(thd, &parser_state, &last_timer, true);
```
?

2019-03-27 20:41 UTC, percona-ysorokin commented on sql/sql_show.cc
> +  virtual void operator()(THD *inspect_thd) {
```suggestion
  virtual void operator()(THD *inspect_thd) override {
```

2019-03-27 20:41 UTC, percona-ysorokin commented on sql/sql_show.cc
> +  size_t m_max_query_length;
It looks like this `m_max_query_length` is never used. Remove?

2019-03-27 20:41 UTC, percona-ysorokin commented on sql/sql_show.cc
> +    DBUG_EXECUTE_IF("processlist_acquiring_dump_threads_LOCK_thd_data", {
This is not used in any MTR test case.

2019-03-27 20:41 UTC, percona-ysorokin commented on sql/sql_show.cc
> +  size_t max_query_length =
Calculated here, and passed to List_transaction_list's constructor but never used inside the class.

2019-03-27 20:41 UTC, percona-ysorokin commented on sql/sql_show.cc
> +    thread_info *thd_info = thread_infos.at(ix);
```suggestion
    thread_info *thd_info = thread_infos[ix];
```

2019-03-27 20:41 UTC, percona-ysorokin commented on sql/sql_show.cc
> +  virtual void operator()(THD *inspect_thd) {
```suggestion
  virtual void operator()(THD *inspect_thd) override {
```

2019-03-27 20:41 UTC, percona-ysorokin commented on sql/sql_show.cc
> +  virtual void operator()(THD *inspect_thd) {
```suggestion
  virtual void operator()(THD *inspect_thd) override {
```

2019-04-03 18:25 UTC, dutow commented
Updated.

2019-04-04 12:20 UTC, percona-ysorokin commented on mysql-test/t/show_transaction_list.test
> +show processlist;
Not addressed

2019-04-05 11:52 UTC, dutow commented on mysql-test/t/show_transaction_list.test
> +show processlist;
I removed this - I only added this for debugging and forgot it there.

2019-04-08 11:19 UTC, percona-ysorokin approved these changes
LGTM

2019-04-18 18:33 UTC, hermanlee commented
Closing this for now and will try to use performance_schema.events_transactions_current to get the transaction times.

2019-04-18 18:33 UTC, closed without merging