WIP FB8-159: Changing thread priorities
facebook/mysql-5.6 pull request #1003
Opened 2019-03-27 10:59 UTC by inikep

Jira issue: https://jira.percona.com/browse/FB8-159

Reference Patch: https://github.com/facebook/mysql-5.6/commit/2971de1

Summary: To change os priorities of thread from mysql

Originally Reviewed By: anirbanr-fb

fbshipit-source-id: fd355ee

TODO: Because of conflicts I removed changes in `mysql-test/t/all_persisted_variables.test`. This test has to be modified at `let $total_persistent_vars=XXX;` (+1 increase) and it should be re-recorded.

2019-03-27 16:21 UTC, percona-ysorokin requested changes

2019-03-27 16:21 UTC, percona-ysorokin commented on sql/sql_class.h
> +    mysql_mutex_lock(&LOCK_thd_data);
May be make `thd_priority_alt` an instance of `std::atomic_bool` to avoid mutex locks?

2019-03-27 16:21 UTC, percona-ysorokin commented on sql/sql_class.h
> +  bool is_thd_priority_alt() { return thd_priority_alt; }
```suggestion
  bool is_thd_priority_alt() const noexcept { return thd_priority_alt; }
```

2019-03-27 16:21 UTC, percona-ysorokin commented on sql/sys_vars.cc
> +    if (delimpos == std::string::npos || delimpos == 0) return false;
This if does not cover a case with trailing colon, like `42:`
may be
```suggestion
    if (delimpos == std::string::npos || delimpos == 0 || delimpos == thd_id_nice_val_str.size() - 1) return false;
```

2019-03-27 16:21 UTC, percona-ysorokin commented on sql/sys_vars.cc
> +  virtual void operator()(THD *thd) {
```suggestion
  virtual void operator()(THD *thd) override {
```

2019-03-27 16:21 UTC, percona-ysorokin commented on sql/sys_vars.cc
> +  bool m_changed;
I would do the following 4 vars private with 2 read-only getters for `m_found` and `m_changed`

2019-03-28 07:00 UTC, laurynas-biveinis commented
MySQL 8.0 has resource groups (https://www.percona.com/blog/2018/01/25/mysql-8-0-resource_group-overview/) which seem to cover this feature completely

2019-04-01 07:08 UTC, closed without merging