WIP FB8-221: Change SET GLOBAL [super_]read_only to not acquire the globa…
facebook/mysql-5.6 pull request #1008
Opened 2019-03-29 08:09 UTC by dutow

…l read lock

Jira ticket: https://jira.percona.com/browse/FB8-221

Reference commit: https://github.com/facebook/mysql-5.6/commit/d8657c3d
Reference commit: https://github.com/facebook/mysql-5.6/commit/a3f808d
Reference commit: https://github.com/facebook/mysql-5.6/commit/8f2dfbd0

-------- a3f808d --------

Change SET GLOBAL [super_]read_only to not acquire the global read lock

Summary:
Currently calling SET GLOBAL [super_]read_only acquires the global read lock before setting the flag and this will block on a long running DML statement.  We think it is safe in our environment to not acquire this lock.

This behavior can be changed back to the original by SET @global.legacy_global_read_lock_mode=1

2019-03-29 09:46 UTC, laurynas-biveinis requested changes

2019-03-29 09:46 UTC, laurynas-biveinis commented on mysql-test/t/global_read_lock.inc
> +real_sleep 1;
Flaky; try replacing real_sleep/SELECT .. FROM processlist pair with wait_for_condition.inc

2019-03-29 09:46 UTC, laurynas-biveinis commented on mysql-test/t/global_read_lock.inc
> +real_sleep 1;
Likewise

2019-03-29 09:46 UTC, laurynas-biveinis commented on mysql-test/t/global_read_lock.test
> +--disable_warnings
Obsolete idiom

2019-03-29 09:46 UTC, laurynas-biveinis commented on mysql-test/t/global_read_lock.test
> +
--source include/count_sessions.inc

2019-03-29 09:46 UTC, laurynas-biveinis commented on mysql-test/t/global_read_lock.test
> +
--source include/wait_until_count_sessions.inc

2019-03-29 09:46 UTC, laurynas-biveinis commented on mysql-test/t/read_only_innodb.test
> +send INSERT INTO t1 (a) select sleep(3) ;
Consider syncing properly

2019-03-29 09:46 UTC, laurynas-biveinis commented on mysql-test/t/read_only_innodb.test
> +--echo echo End of 5.1 tests
Redundant diff

2019-03-29 09:46 UTC, laurynas-biveinis commented on mysql-test/t/read_only_innodb_basic.test
> +DROP TABLE IF EXISTS t1,t2,t3;
Obsolete idiom

2019-03-29 13:17 UTC, percona-ysorokin requested changes

2019-03-29 13:17 UTC, percona-ysorokin commented on mysql-test/suite/sys_vars/t/legacy_global_read_lock_mode_basic.test
> +CREATE TABLE valid_values (value VARCHAR(255)) ENGINE=myisam;
Either `--source include/have_myisam.inc` or remove ` ENGINE=myisam`.

2019-03-29 13:17 UTC, percona-ysorokin commented on mysql-test/suite/sys_vars/t/legacy_global_read_lock_mode_basic.test
> +CREATE TABLE invalid_values (value VARCHAR(255)) ENGINE=myisam;
Likewise

2019-04-10 08:00 UTC, dutow commented
Updated.

2019-04-30 07:20 UTC, dutow commented
Updated.

2019-05-02 10:20 UTC, percona-ysorokin approved these changes
LGTM

2019-05-24 00:47 UTC, hermanlee approved these changes

2019-06-19 15:52 UTC, closed without merging