WIP FB8-118: Port slow query log rotation
facebook/mysql-5.6 pull request #1015
Opened 2019-04-11 15:30 UTC by inikep

Jira issue: https://jira.percona.com/browse/FB8-118

Reference Patch: https://github.com/facebook/mysql-5.6/commit/3445f81

Porting notes:
1. fixed PS-1484: slowlog rotation and expiration doesn't work with the default slow query log name
2. `max_slowlog_files` was replaced with `slowlog_space_limit`

---------- https://github.com/facebook/mysql-5.6/commit/3445f81 ----------

Summary:
This diff is a combination of the following two commits from Percona:
https://github.com/percona/percona-server/commit/725a238c
https://github.com/percona/percona-server/commit/85c461c8

Adds two new variables `max_slowlog_size` and `max_slowlog_files` as documented here:
https://www.percona.com/doc/percona-server/LATEST/flexibility/slowlog_rotation.html

Originally Reviewed By: hermanlee

fbshipit-source-id: 746c6bf

2019-04-12 09:42 UTC, percona-ysorokin requested changes

2019-04-12 09:42 UTC, percona-ysorokin commented on mysql-test/t/percona_slowlog_size_limits.test
> +SET @old_long_query_time = @@long_query_time;
Redundant - it's OK to modify session variables
```suggestion
```

2019-04-12 09:42 UTC, percona-ysorokin commented on mysql-test/t/percona_slowlog_size_limits.test
> +printf "%d\n", scalar(@files);
May be write this `scalar(@files)` to a temp file (something like `$MYSQL_TMP_DIR/list_result.inc`) inside this `--perl` block in format
```perl
printf FILEHANDLE "--let \$number_of_files = %d\n", scalar(@files);`
```
and then include this file in MTR immediately after the `--perl` block
```
--source $MYSQL_TMP_DIR/list_result.inc
```
This way you will be able to assert `$number_of_files == nnn`.

At the end, do not forget to remote this `$MYSQL_TMP_DIR/list_result.inc`

2019-04-12 09:42 UTC, percona-ysorokin commented on mysql-test/t/percona_slowlog_size_limits.test
> +printf "%d\n", scalar(@files);
likewise

2019-04-12 09:42 UTC, percona-ysorokin commented on mysql-test/t/percona_slowlog_size_limits.test
> +printf "%d\n", scalar(@files);
likewise

2019-04-12 09:42 UTC, percona-ysorokin commented on mysql-test/t/percona_slowlog_size_limits.test
> +printf "%d\n", scalar(@files);
likewise

2019-04-12 09:42 UTC, percona-ysorokin commented on mysql-test/t/percona_slowlog_size_limits.test
> +printf "%d\n", scalar(@files);
likewise

2019-04-12 09:42 UTC, percona-ysorokin commented on mysql-test/t/percona_slowlog_size_limits.test
> +printf "%d\n", scalar(@files);
likewise

2019-04-12 09:42 UTC, percona-ysorokin commented on mysql-test/t/percona_slowlog_size_limits.test
> +printf "%d\n", scalar(@files);
likewise

2019-04-12 09:42 UTC, percona-ysorokin commented on mysql-test/t/percona_slowlog_size_limits.test
> +printf "%d\n", scalar(@files);
likewise

2019-04-12 09:42 UTC, percona-ysorokin commented on mysql-test/t/percona_slowlog_size_limits.test
> +printf "%d\n", scalar(@files);
likewise

2019-04-12 09:42 UTC, percona-ysorokin commented on mysql-test/t/percona_slowlog_size_limits.test
> +SET @@long_query_time = @old_long_query_time;
Redundant
```suggestion
```

2019-04-12 09:42 UTC, percona-ysorokin commented on mysql-test/t/percona_slowlog_size_limits.test
> +
```suggestion
--remove_file $MYSQL_TMP_DIR/list_result.inc
```
See above

2019-04-12 12:03 UTC, inikep commented
PR was updated according to comments.

2019-04-15 13:33 UTC, percona-ysorokin approved these changes
LGTM

2019-05-24 19:31 UTC, hermanlee approved these changes

2019-06-11 18:03 UTC, closed without merging