Print the last acked position when a semi-sync slave connects to the master
facebook/mysql-5.6 pull request #1077
Opened 2020-01-06 23:16 UTC by percona-ysorokin

Summary:
This information will be helpful in debugging.

Reference Patch: facebook/mysql-5.6@dc0940c

Originally Reviewed By: guokeno0

2020-01-09 01:15 UTC, hermanlee commented on sql/binlog.cc
> +      sql_print_information("Signalling async threads to pos: %s:%llu",
Doesn't this trigger printing to the error log after each group commit? We're only looking to print out the async threads position when a semi-sync slave connects to the server.

2020-01-10 02:22 UTC, hermanlee commented on sql/binlog.cc
> +      sql_print_information("Signalling async threads to pos: %s:%llu",
Indeed, what I'm seeing in the error log for each insert statement on the master:

2020-01-10T02:21:00.973077Z 8 [Note] [MY-010462] [Repl] Start binlog_dump to master_thread_id(8) slave_server(2), pos(, 4)
2020-01-10T02:21:11.128362Z 9 [Note] [MY-000000] [Server] Signalling async threads to pos: master-bin.000001:374
2020-01-10T02:21:13.446666Z 9 [Note] [MY-000000] [Server] Signalling async threads to pos: master-bin.000001:648
2020-01-10T02:21:14.938622Z 9 [Note] [MY-000000] [Server] Signalling async threads to pos: master-bin.000001:922
2020-01-10T02:21:34.745018Z 9 [Note] [MY-000000] [Server] Signalling async threads to pos: master-bin.000001:1196
2020-01-10T02:21:36.329375Z 9 [Note] [MY-000000] [Server] Signalling async threads to pos: master-bin.000001:1470
2020-01-10T02:21:45.940968Z 9 [Note] [MY-000000] [Server] Signalling async threads to pos: master-bin.000001:1744

2020-01-10 02:23 UTC, hermanlee requested changes
This needs to be fixed so that the logging only happens when a semi-sync slave connects to the server.

2020-01-15 15:41 UTC, percona-ysorokin commented
@hermanlee Got you. Will rework the fix.

2020-01-20 17:07 UTC, percona-ysorokin commented
PR updated

2020-01-22 01:37 UTC, percona-ysorokin commented
PR updated one more time (even better implementation)

2020-01-22 15:56 UTC, percona-ysorokin commented
PR updated one more time (Better function names)

2020-01-22 23:17 UTC, hermanlee commented on sql/mysqld.cc
> +  mysql_bin_log.print_last_acked_pos();
It seems like this function is only called during server initialization, vs. whenever a semi-sync slave connects to the server?

It seems like ReplSemiSyncMaster::add_slave() would be a better place for this call?

2020-02-06 17:51 UTC, hermanlee commented
It would be fine to drop this PR.

2020-02-06 17:51 UTC, closed without merging