make insert_duplicate_key_update_race test more stable
facebook/mysql-5.6 pull request #1092
Opened 2020-01-20 16:52 UTC by inikep

Summary: Valgrind run may let id generated in different order. Let's only verify the content, but without id

Originally Reviewed By: abhinav04sharma

fbshipit-source-id: 38f02037be3

Reference Patch: https://github.com/facebook/mysql-5.6/commit/03919677cb5

-----------------------------------------------------------------

make innodb.insert_duplicate_key_update_race more stable

Summary: insert_duplicate_key_update_race can generate data in none deterministic order. Add oder by to make it has an consist data output order

Originally Reviewed By: yizhang82

fbshipit-source-id: 3b4deab

Reference Patch: https://github.com/facebook/mysql-5.6/commit/2c2afd33a50

2020-01-20 17:05 UTC, percona-ysorokin requested changes

2020-01-20 17:05 UTC, percona-ysorokin commented on mysql-test/suite/innodb/t/insert_duplicate_key_update_race.test
> +  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
Remove integer width specifier
```suggestion
  id bigint unsigned NOT NULL AUTO_INCREMENT,
```

2020-01-20 17:05 UTC, percona-ysorokin commented on mysql-test/suite/innodb/t/insert_duplicate_key_update_race.test
> +--source include/wait_until_count_sessions.inc
Add
```
set DEBUG_SYNC = "RESET";
```

2020-01-20 17:14 UTC, percona-ysorokin approved these changes
LGTM

2020-01-23 22:12 UTC, hermanlee commented
It looks like 8.0.19 has this fix already. Going to backport the change cbd87693248.

2020-01-23 22:12 UTC, closed without merging