[WIP] Adding options to do blind deletes and not to use tx api
facebook/mysql-5.6 pull request #1129
Opened 2020-05-05 10:11 UTC by oleksandr-kachan

Reference Patch: https://github.com/facebook/mysql-5.6/commit/1245598bf1e

---------- https://github.com/facebook/mysql-5.6/commit/1245598bf1e ----------
Summary:
This diff adds two session variables to allow some operations faster.
- rocksdb_blind_delete_primary_key -- Executing deletes without calling
GetForUpdate(). To use this feature, target table must have primary key
only (no secondary key). No multi-table operations are allowed.
- rocksdb_master_skip_tx_api -- Not using transaction api on master.
This means no row locks are held during row modifications. It's user's
responsibility to make operations safe.

Benchmark results -- deleting 100k rows with bulk deletes (1000 row
deletes per statement).
 1) Normal -- 1.448s
 2) rocksdb_blind_delete_primary_key -- 0.671s
 3) 2) + rocksdb_master_skip_tx_api -- 0.324s

Originally Reviewed By: hermanlee

fbshipit-source-id: fa5c138862e

2020-05-15 12:15 UTC, percona-ysorokin requested changes

2020-05-15 12:15 UTC, percona-ysorokin commented on mysql-test/suite/rocksdb/t/blind_delete_without_tx_api.test
> +set @save_rocksdb_blind_delete_primary_key=@@session.rocksdb_blind_delete_primary_key;
There is no need to save/restore SESSION variables. This technique is only needed for GLOBAL ones.

2020-05-15 12:15 UTC, percona-ysorokin commented on mysql-test/suite/rocksdb/t/blind_delete_without_tx_api.test
> +set @save_rocksdb_master_skip_tx_api=@@session.rocksdb_master_skip_tx_api;
Likewise

2020-05-15 12:15 UTC, percona-ysorokin commented on mysql-test/suite/rocksdb/t/blind_delete_without_tx_api.test
> +DROP TABLE IF EXISTS t1,t2;
Ancient MTR idiom - no need to delete tables before creating them. MTR now always start from a clean state.

2020-05-15 12:15 UTC, percona-ysorokin commented on mysql-test/suite/rocksdb/t/blind_delete_without_tx_api.test
> +set session rocksdb_blind_delete_primary_key=@save_rocksdb_blind_delete_primary_key;
No need to save/restore SESSION variables

2020-05-15 12:15 UTC, percona-ysorokin commented on mysql-test/suite/rocksdb/t/blind_delete_without_tx_api.test
> +set session rocksdb_master_skip_tx_api=@save_rocksdb_master_skip_tx_api;
Likewise

2020-05-22 14:54 UTC, percona-ysorokin approved these changes
LGTM

2020-06-23 00:21 UTC, hermanlee reviewed
It looks like there are some later changes to the tests which were not in the original list.

Could you update this patch to include the test changes from

[mysql-5.6][PR] Skip snapshot validation on Read Committed
https://github.com/facebook/mysql-5.6/commit/dfbb8ffd7b0d6f1c8f3cb211edcc446ced5badee

too? It looks like the test gets refactored to support both read-committed and repeatable-read isolation levels.

2020-06-23 13:25 UTC, oleksandr-kachan commented
> Could you update this patch to include the test changes from
> 
> [mysql-5.6][PR] Skip snapshot validation on Read Committed
> [dfbb8ff](https://github.com/facebook/mysql-5.6/commit/dfbb8ffd7b0d6f1c8f3cb211edcc446ced5badee)
> 
> too? It looks like the test gets refactored to support both read-committed and repeatable-read isolation levels.

Just to recheck. Isn't this change already done for 8.0.17 in https://github.com/facebook/mysql-5.6/commit/d433e614f566ff83f31219a3f3cd93a80e689b7f#diff-924972e9288665ca701c6a69ccf484fc

2020-06-23 16:11 UTC, hermanlee commented
Ah, yes, it has been ported. That change had renamed the rocksdb.blind_delete_without_tx_api test to rocksdb.blind_delete_rc, but this change re-introduces rocksdb.blind_delete_without_tx_api, which is what confused me. It looks like this patch is already in 8.0.17 then, but renamed to the blind_delete_r[rc] tests. We should be able to close this request then. Thanks!

2020-06-23 16:11 UTC, closed without merging