[WIP] Dump core for mysqld without large memory buffer
facebook/mysql-5.6 pull request #1132
Opened 2020-05-13 12:43 UTC by oleksandr-kachan

Reference Patch: https://github.com/facebook/mysql-5.6/commit/e31a21144b8

---------- https://github.com/facebook/mysql-5.6/commit/e31a21144b8 ----------
Summary:
Core files can be very helpful for debugging production crashes but core dump has been disabled on production due to multiple reasons. One of the reasons is that the core file can be huge due to the huge InnoDB buffer pool within the process. This diff introduces a new command line argument '--innodb-dump-core-without-large-mem-buf', when it is set, all the large memory allocation by function os_mem_alloc_large() in InnoDB won't be dumped in the core file by calling Linux API madvise() with argument MADV_DONTDUMP. It can be disabled by '--skip-innodb-dump-core-without-large-mem-buf'. os_mem_alloc_large() is used to allocate large memory chunk for InnoDB buffer pool, file data merge, row log buffer, etc. Buffer pool is the main one. With this feature, the core size will be less than 3GB when the buffer pool size is 60GB so it won't impact production.
-- This sys var only take effect when core dump is enabled by setting 'core-file' in my.cnf.
-- By default '--innodb-dump-core-without-large-mem-buf' is set in prod to dump smaller cores, but it is not set by default in MTR so that full core file can be dumped.
-- This diff also makes sys var core_file readonly.
-- There are other bugs that prevent mysqld from dumping cores, e.g. when mysqld switching user from root to a non-root user, etc. Those will be addressed in separated diffs.

Originally Reviewed By: jtolmer

fbshipit-source-id: 119924337ab

2020-05-15 13:06 UTC, percona-ysorokin requested changes

2020-05-15 13:06 UTC, percona-ysorokin commented on mysql-test/suite/innodb/t/mysqld_core_dump_without_large_mem_buf.test
> +--source include/wait_until_connected_again.inc
Use `restart_mysqld.inc` / `restart_mysqld_no_echo.inc` instead
```suggestion
--let $restart_parameters = restart:--log-error=$MYSQLTEST_VARDIR/log/core_dump.err
--source include/restart_mysqld.inc
```

2020-05-15 13:06 UTC, percona-ysorokin commented on mysql-test/suite/innodb/t/mysqld_core_dump_without_large_mem_buf_with_resizing.test
> +--source include/wait_until_connected_again.inc
Likewise

2020-05-15 13:06 UTC, percona-ysorokin commented on mysql-test/suite/innodb/t/mysqld_core_dump_without_large_mem_buf.test
> +
Consider making this test `--source include/big_test.inc` as it request 60GB buffer pool

2020-05-15 13:06 UTC, percona-ysorokin commented on mysql-test/suite/innodb/t/mysqld_core_dump_without_large_mem_buf_with_resizing.test
> +
Consider making this test `--source include/big_test.inc` as it request 60GB buffer pool

2020-05-22 15:00 UTC, percona-ysorokin approved these changes
LGTM

2020-06-04 21:22 UTC, hermanlee commented
Sorry, we made a mistake adding this change to the list. The change was already upstreamed to Oracle and in 8.0.14:

commit 891460995137598a6e0ae3684ba1cc6ccd0c3ca3
Author: Jakub Łopuszański <jakub.lopuszanski@oracle.com>
Date:   Wed Aug 29 13:27:14 2018 +0200

    Bug #27724476   CONTRIBUTION BY FACEBOOK: DETACH INNODB BUFFER POOL BEFORE CREATING CORE

Since it's already been ported, I'll close out this PR.

2020-06-04 21:22 UTC, closed without merging