Add ROCKSDB_COMPACTION_STATS table
facebook/mysql-5.6 pull request #422
Opened 2016-11-14 17:43 UTC by maysamyabandeh

2016-11-16 04:00 UTC, maysamyabandeh commented
@hermanlee The patch is ready for review. Thanks for all the offline help.

@reidHoruff @lth adding you as the reviewer per Herman's request.  I would appreciate your comments on the submitted patch.

2016-11-17 17:04 UTC, maysamyabandeh commented
The sandcastle tests fails with this error: 
```
rocksdb.rocksdb_deadlock_stress_rr       w14 [ fail ]
        Test ended at 2016-11-16 19:42:44
CURRENT_TEST: rocksdb.rocksdb_deadlock_stress_rr
mysqltest: In included file "./suite/rocksdb/t/rocksdb_deadlock_stress.inc": 
included from ./suite/rocksdb/t/rocksdb_deadlock_stress.inc at line 14:
At line 14: command "python suite/rocksdb/t/rocksdb_deadlock_stress.py root 127.0.0.1 $MASTER_MYPORT test t1 10000 10" failed
Output from before failure:
exec of 'python suite/rocksdb/t/rocksdb_deadlock_stress.py root 127.0.0.1 13140 test t1 10000 10' failed, error: 139, status: 0, errno: 11
```

I tried it on my devvm and it failed with this error:
```
CURRENT_TEST: rocksdb.rocksdb_deadlock_stress_rr
Traceback (most recent call last):
  File "suite/rocksdb/t/rocksdb_deadlock_stress.py", line 9, in <module>
    import MySQLdb
```
Then I installed the missing package:
```
sudo yum install MySQL-python
```
 and the tests passes now:
```
rocksdb.rocksdb_deadlock_stress_rr       [ pass ]  171954  
```

I am not sure if sandcastle is failing for the same issue or not. Any thoughts?

2016-11-18 22:44 UTC, maysamyabandeh commented
@reidHoruff @lth a kind reminder for comments :) Thanks.

2016-11-23 22:08 UTC, hermanlee requested changes
Is the rocksdb submodule update still needed?

Other than that, changes look good to me.

2016-11-23 22:08 UTC, hermanlee commented on storage/rocksdb/rdb_i_s.cc
> +      ret |= my_core::schema_table_store_record(thd, tables->table);
If ret is non-zero, should probably break out at this point since further record stores could be problematic.

2016-11-23 22:08 UTC, hermanlee commented on storage/rocksdb/rdb_i_s.cc
> +    if (cfh == nullptr)
Add { } around the single line body to prevent problems in the future. Not all if's in the file do this, but we've been moving in this direction.

2016-11-23 22:21 UTC, maysamyabandeh commented
Thanks for the review. No rocksdb is already updated in this commit 68a7711fbc1b82d8a37fe282e98dd3151b2054db and no longer needed to be updated

2016-11-23 23:55 UTC, hermanlee commented
Can you update the pull request with the new diff and remove the rocksdb change?

2016-12-29 22:37 UTC, hermanlee approved these changes

2017-01-03 17:55 UTC, maysamyabandeh commented
@hermanlee sandcastle reports some test failures although i cannot find any failed tests. Does it sound like a false alarm?

https://our.intern.facebook.com/intern/sandcastle/log/?instance_id=285257184&name=sandcastle
```
Unit tests: 100% tests passed, 0 tests failed out of 22
Completed All Requested MySQL Testing
2017-01-03 09:09:10 3882219 [Note] Shutting down plugin 'MyISAM'
mysql-test-run: *** ERROR: there were failing test cases
```

2017-01-03 20:52 UTC, lth commented
You need to update main.mysqld--help-notwin-profiling.

2017-01-04 03:38 UTC, maysamyabandeh commented
The failed unit test seems irrelevant:
```
main.index_merge_innodb                  w8 [ fail ]
        Test ended at 2017-01-03 15:31:48
CURRENT_TEST: main.index_merge_innodb
--- /data/sandcastle/boxes/instance-mysql-int-git-mysql-diff-debug-parallelbig-noperfschema/mysql-test/r/index_merge_innodb.result	2017-01-04 01:13:57.476855171 +0300
+++ /data/sandcastle/boxes/instance-mysql-int-git-mysql-diff-debug-parallelbig-noperfschema/_build-5.6-Debug/mysql-test/var/8/log/index_merge_innodb.reject	2017-01-04 02:31:47.867049742 +0300
@@ -697,7 +697,7 @@
 key1	key2	filler1
 explain select key1,key2,key3,key4,filler1 from t1 where key1=100 and key2=100 or key3=100 and key4=100;
 id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra
-1	SIMPLE	t1	index_merge	key1,key2,key3,key4	key1,key2,key3,key4	5,5,5,5	NULL	4	Using union(intersect(key1,key2),intersect(key3,key4)); Using where
+1	SIMPLE	t1	index_merge	key1,key2,key3,key4	key1,key2,key4,key3	5,5,5,5	NULL	4	Using union(intersect(key1,key2),intersect(key4,key3)); Using where
 select key1,key2,key3,key4,filler1 from t1 where key1=100 and key2=100 or key3=100 and key4=100;
 key1	key2	key3	key4	filler1
 -1	-1	100	100	key4-key3
```
It is also passes on my vm.
@hermanlee Do I have your +1 for landing?

2017-01-05 18:26 UTC, closed without merging