Adding delayed_write_rate RocksDB option for MyRocks
facebook/mysql-5.6 pull request #526
Opened 2017-02-09 18:50 UTC by xiaofeidu008

Summary: Currently delayed_write_rate is not configurable in MySQL. This
diff adds the configuration to MySQL so it can be configured in MySQL

Test Plan: ran rocksdb_sys_vars test suite

Reviewers: yoshinori

Subscribers:

Tasks: 15979933

Blame Revision:

2017-02-09 19:13 UTC, alxyang requested changes
I think you may need to rerecord rocksdb.rocksdb as well.

2017-02-10 19:30 UTC, alxyang commented
be sure to close https://github.com/facebook/mysql-5.6/issues/517 after this lands

2017-02-10 19:42 UTC, lth commented
Alternatively, you can edit your comment above and add "Closes #517". The comment becomes your commit message when it lands.

2017-02-10 21:06 UTC, xiaofeidu008 commented
@alxyang @lth I have updated the title and commit message. I will close 517 later

2017-02-10 21:34 UTC, alxyang commented on mysql-test/r/mysqld--help-notwin.result
> -secure-file-priv (No default value)
this line shoudn't be removed as part of this diff.  Looks like @anirbanr-fb forgot to re-record this test in https://github.com/facebook/mysql-5.6/commit/04a32957d785e4546535c754cef9f9768e5c9d0f#diff-0f69f98e011b11eac33c99987aa19fb8.  I'll make a commit removing it which you can rebase your changes on top of.

2017-02-10 21:43 UTC, xiaofeidu008 commented on mysql-test/r/mysqld--help-notwin.result
> -secure-file-priv (No default value)
@alxyang sounds good. Let me know when it's done. Thanks

2017-02-10 22:09 UTC, alxyang commented on mysql-test/r/mysqld--help-notwin.result
> -secure-file-priv (No default value)
5831460810505ba98bcdce9683131b7a0296fdff

2017-02-10 22:34 UTC, alxyang approved these changes
lgtm

2017-02-14 00:07 UTC, closed without merging

2017-02-14 01:05 UTC, xiaofeidu008 commented
@alxyang @lth I don't have permission to close #517. Could you please close it? Thanks much

2017-02-14 01:20 UTC, alxyang commented
done

2017-02-14 01:22 UTC, xiaofeidu008 commented
@alxyang Thanks