Correctly handle setting auto increment to largest value
facebook/mysql-5.6 pull request #556
Opened 2017-03-03 01:39 UTC by jkedgar

Summary: The auto increment code in MyRocks allowed a wrap-around, yield incorrect results

Test Plan: MTR and new rocksdb.issue255 test

2017-03-03 03:29 UTC, laurynas-biveinis commented on storage/rocksdb/ha_rocksdb.cc
> +  if (new_val + 1 > new_val) {  // don't increment if we would wrap around
Isn't this relying on the undefined behavior of signed integer overflow?

2017-03-03 03:32 UTC, laurynas-biveinis commented on storage/rocksdb/ha_rocksdb.cc
> +  if (new_val + 1 > new_val) {  // don't increment if we would wrap around
...whereas the next snippet checks against "std::numeric_limits<longlong>::max()" without UB

2017-03-03 03:34 UTC, laurynas-biveinis commented on storage/rocksdb/ha_rocksdb.cc
>        new_val = ((last_val + (inc - off) - 1) / inc) * inc + off;
AFAICT this a (pre-existing) undefined behavior too

2017-03-03 16:58 UTC, jkedgar commented
Good calls @laurynas-biveinis.  I was getting lazy.  There's a difference between using code that you know will work on 99.999% of the servers in existence and using code that you know will always work.  I'll fix all of the mentioned issues.

2017-03-07 06:28 UTC, hermanlee requested changes

2017-03-07 06:28 UTC, hermanlee commented on storage/rocksdb/ha_rocksdb.cc
> +      auto_incr++;
This change breaks auto-increment and two concurrent calls can end up returning the same "first_value". If you want to check before the increment, I think you need to switch this to a cas call.

2017-03-07 06:28 UTC, hermanlee commented on storage/rocksdb/ha_rocksdb.cc
> +        auto_incr = new_val; // Store the largest value into auto_incr
Blindly setting auto_incr to max value can cause auto_incr to overflow when combined with concurrent calls to auto_incr++. Again, I think you need to perform a cas here to do this correctly.

2017-03-09 21:28 UTC, jkedgar commented on storage/rocksdb/ha_rocksdb.cc
> +      auto_incr++;
You are absolutely correct.  I'm getting lazy.  :(

2017-03-09 21:28 UTC, jkedgar commented on storage/rocksdb/ha_rocksdb.cc
> +        auto_incr = new_val; // Store the largest value into auto_incr
I agree that the way it is in the other one (with auto_incr++) this has the possibility of overflow, but once I fix that to use a cas I don't think I need to change this here.

2017-03-13 19:56 UTC, hermanlee approved these changes
Thanks for fixing this!

2017-03-14 22:37 UTC, closed without merging