Issue#857: MyRocks: Incorrect behavior when miltiple statements fail …
facebook/mysql-5.6 pull request #858
Opened 2018-07-13 18:40 UTC by spetrunia

…inside a transaction

rollback_to_stmt_savepoint() calls do_rollback_to_savepoint(). This
removes the changes made by this statement, and also removes the last
set savepoint.

Before we start processing the next statement, we need to set the new
savepoint, so we will have something to rollback to if the next statement
fails.

Since rollback_to_stmt_savepoint always sets a new savepoint now,
m_n_savepoints is now redundant and is removed.

2018-07-16 18:07 UTC, hermanlee requested changes
Can you also update the description with:

Squash with D7509380

On a new rebase, we'll merge this fix with the original change.

2018-07-16 18:07 UTC, hermanlee commented on mysql-test/suite/rocksdb/r/transaction.result
> +# Issue#857: MyRocks: Incorrect behavior when miltiple statements fail inside a transaction
nit: typo: multiple

2018-07-16 18:07 UTC, hermanlee commented on storage/rocksdb/ha_rocksdb.cc
> -    m_n_savepoints= 1;
Since this is not longer used, the definition in Rdb_transaction should also be removed.

2018-07-18 09:28 UTC, spetrunia commented on storage/rocksdb/ha_rocksdb.cc
> -    m_n_savepoints= 1;
Done

2018-07-18 09:29 UTC, spetrunia commented
Addressed all review input.

2018-07-19 20:14 UTC, hermanlee approved these changes

2018-07-23 18:26 UTC, closed without merging