Issue-895 : rocksdb/env/io_posix.cc:449: rocksdb::PosixMmapReadableFi…
facebook/mysql-5.6 pull request #897
Opened 2018-11-01 21:26 UTC by georgelorchpercona

…le::PosixMmapReadableFile(int, const string&, void*, size_t, const rocksdb::EnvOptions&): Assertion `!options.use_direct_reads' failed.

- Extended previous fix fo Issue 778 to also check if
  rocksdb_use_direct_io_for_flush_and_compaction=1 is being used on tmpfs.
  Duplicated simple test that skips when on tmpfs.

2018-11-07 09:32 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/use_direct_io_for_flush_and_compaction.test
> +--perl
This is copy-paste with use_direct_reads.test - begs for an include file

2018-11-26 16:41 UTC, hermanlee requested changes
Refactor tests

2018-11-27 07:20 UTC, laurynas-biveinis reviewed
What I had in mind to was to factor out some skip_if_data_in_dev_shm.inc, but this looks good to me too :)

2019-02-05 16:40 UTC, hermanlee commented
I found another test was broken, so I refactored headers into have_direct_io.inc. A better name would be have_not_in_shm.inc though, but this should be fine.

2019-02-05 16:40 UTC, closed without merging