WIP FB8-56: Create a new mode SEMI_STRICT for slave_exec_mode
facebook/mysql-5.6 pull request #941
Opened 2019-01-25 15:07 UTC by inikep

Summary:
Create a new mode SEMI_STRICT which ignores HA_ERR_RECORD_CHANGED and HA_ERR_KEY_NOT_FOUND errors.
A new status counter will track the usage of this new mode. Logging a warning/error message may cause error
log to get flooded with same error message, so I decided against it.

JIRA: https://jira.percona.com/browse/FB8-56

This patch ports the following commit: https://github.com/facebook/mysql-5.6/commit/9d97282

2019-01-25 17:53 UTC, percona-ysorokin requested changes

2019-01-25 17:53 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_slave_exec_mode_semi_strict.test
> +sync_slave_with_master;
use `--source include/sync_slave_sql_with_master.inc` instead

2019-01-25 17:53 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_slave_exec_mode_semi_strict.test
> +sync_slave_with_master;
use `--source include/sync_slave_sql_with_master.inc` instead

2019-01-25 17:53 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_slave_exec_mode_semi_strict.test
> +create table t1 (a int primary key, b int) engine=Innodb;
UPPER case for SQL keywords

2019-01-25 17:53 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_slave_exec_mode_semi_strict.test
> +show global status like 'Rbr_unsafe_queries';
Make sure this test passes with `--repeat=2`. If not, save initial value `Rbr_unsafe_queries`, do delete and then assert that `Rbr_unsafe_queries` changed by 1.

2019-01-25 17:53 UTC, percona-ysorokin commented on sql/mysqld.cc
> +    {"Rbr_unsafe_queries", (char *)&rbr_unsafe_queries, SHOW_LONGLONG,
Does this new status var need to be reflected in `perfschema.show_sanity` MTR test case?

2019-01-28 09:27 UTC, inikep commented on sql/mysqld.cc
> +    {"Rbr_unsafe_queries", (char *)&rbr_unsafe_queries, SHOW_LONGLONG,
There is no `perfschema.show_sanity` in 8.0

2019-01-28 10:10 UTC, inikep commented
PR was updated with requested changes

2019-01-29 10:51 UTC, percona-ysorokin approved these changes
LGTM

2019-02-02 00:37 UTC, hermanlee approved these changes

2019-02-05 20:26 UTC, closed without merging