WIP FB8-77: Changed the behavior of purging logs. Now deleting logs first and then updating the index
facebook/mysql-5.6 pull request #943
Opened 2019-01-29 13:37 UTC by inikep

Summary: Previously when purging logs, the index was updated before deleting the logs. This creates problems the disk is full. We should first delete logs to free up disk and then update index.

JIRA: https://jira.percona.com/browse/FB8-77

This patch ports the following commits:
https://github.com/facebook/mysql-5.6/commit/832be30
https://github.com/facebook/mysql-5.6/commit/0d85250
https://github.com/facebook/mysql-5.6/commit/e8be5be

2019-01-29 15:49 UTC, percona-ysorokin requested changes

2019-01-29 15:49 UTC, percona-ysorokin commented on sql/binlog.cc
> +  std::list<std::string> delete_list;
`typedef / using` for a complex container type

2019-01-29 15:49 UTC, percona-ysorokin commented on sql/binlog.cc
> +    delete_list.push_back(std::string(log_info.log_file_name));
`delete_list.emplace_back(log_info.log_file_name)`

2019-01-29 15:49 UTC, percona-ysorokin commented on sql/binlog.cc
> +  std::list<std::string> delete_list;
typedef / using for a complex container type

2019-01-29 15:49 UTC, percona-ysorokin commented on sql/binlog.cc
> +      delete_list.push_back(std::string(log_info.log_file_name));
`delete_list.emplace_back(log_info.log_file_name)`

2019-01-29 15:49 UTC, percona-ysorokin commented on sql/binlog.cc
> +int MYSQL_BIN_LOG::purge_logs_in_list(std::list<std::string> &delete_list,
`int MYSQL_BIN_LOG::purge_logs_in_list(const log_file_name_container& delete_list, ...`

See below for `log_file_name_container`

2019-01-29 15:49 UTC, percona-ysorokin commented on sql/binlog.cc
> +  for (auto &log_file_name : delete_list) {
`const auto &`

2019-01-29 15:49 UTC, percona-ysorokin commented on sql/binlog.h
> +  int purge_logs_in_list(std::list<std::string> &delete_list, THD *thd,
Define using log_file_name_container = std::list<std::string> here.
`int purge_logs_in_list(const log_file_name_container& delete_list, ...`

2019-01-30 09:51 UTC, inikep commented
PR was updated with requested changes

2019-01-30 10:10 UTC, percona-ysorokin approved these changes
LGTM

2019-02-04 15:25 UTC, hermanlee approved these changes

2019-02-05 20:16 UTC, closed without merging