WIP FB8-48: Option to run triggers on slave for row-based events
facebook/mysql-5.6 pull request #946
Opened 2019-01-31 16:14 UTC by inikep

JIRA: https://jira.percona.com/browse/FB8-48

This patch ports the following commits:
1. https://github.com/facebook/mysql-5.6/commit/8225c64
2. https://github.com/facebook/mysql-5.6/commit/f5466d6
3. https://github.com/facebook/mysql-5.6/commit/87e3650

================================ COMMIT 1 ================================

Option to run triggers on slave for row-based events

Summary:
Port the slave_run_triggers_for_rbr feature from mariadb 10.1.1.

When using statement based replication slave executes the sql statments
which runs the slave side triggers. Since in row based replication, slave
applies the row events directly to the storage engine, triggers on the slave
table are not executed. Add functionality to run triggers on slave side
when executing row based events.

The following triggers are invoked:

* Update_row_event runs an UPDATE trigger
* Delete_row_event runs a DELETE trigger
* Write_row_event action depends on whether the operation will require foreign key checks:
  1) when FK checks are not necessary, the operation will invoke a DELETE trigger if the record
  to be modified existed in the table. After that, an INSERT trigger will be invoked.
  2) when FK checks are necessary, either an UPDATE or or a combination of
     DELETE and INSERT triggers will be invoked.

slave_run_triggers_for_rbr option controls the feature.
Default value is NO which don't invoke trigger for row-based events; Setting the option
to YES will cause the SQL slave thread to invoke triggers for row based events; setting it to
LOGGING will also cause the changes made by the triggers to be written into the binary log.

There is a basic protection against triggers being invoked both on the master and slave.
If the master modifies a table that has triggers, it will produce row-based binlog events
with the "triggers were invoked for this event" flag. The slave will not invoke any
triggers for flagged events.

Test Plan: mtr tests

================================ COMMIT 2 ================================

optionally disable binlogging while executing triggers

Summary:
Online schema change (OSC) creates triggers only on master side. Since RBR logs row changes made by triggers, sql_thread will hit errors due to missing tables on slaves. Add a session variable SQL_LOG_BIN_TRIGGERS to optionally disable binlogging for trigger statements so that RBR and OSC are fine with each other.

disable_sql_log_bin_triggers flag is added in the TABLE_LIST struct to track tables that are opened during trigger execution. This flag is used to skip writing Table_map_log_events for such tables.

With sql_log_bin_triggers enabled, the trigger changes which may be necessary for slave are not propagated. To avoid this, slave_run_triggers_for_rbr option must be enabled on slave.

Test Plan: mtr tests

================================ COMMIT 3 ================================

Another attempt to fix rpl.rpl_unsafe_statements

Summary:
The rpl.rpl_unsafe_statements test was added in 5.6.29 and when we rebased to 5.6.35 it started causing a problem with the diff "optionally disable binlogging while executing triggers".  This is an attempt to modify that diff to work correctly for this case.

Squash with: https://github.com/facebook/mysql-5.6/commit/cdeb01291f4d5440f07a33ad5f53245ed302e617

Differential Revision: D4836512

fbshipit-source-id: https://github.com/facebook/mysql-5.6/commit/87e36503c4177bdd91c54c341a2cb73a5f50d6fc

2019-02-01 07:57 UTC, laurynas-biveinis requested changes
Lots of tiny mechanical improvement comments. mysqld--help-notwin.result changes are suspicious

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +connection master;
Redundant: master-slave.inc finishes at master connection
```suggestion
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +sync_slave_with_master;
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +connection slave;
Redundant: slave syncs finish at slave connection
```suggestion
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +sync_slave_with_master;
--source include/sync_slave_sql_with_master.inc

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +connection slave;
```suggestion
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +sync_slave_with_master;
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +connection slave;
```suggestion
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +sync_slave_with_master;
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +connection slave;
```suggestion
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +sync_slave_with_master;
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +connection slave;
```suggestion
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +sync_slave_with_master;
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +connection slave;
```suggestion
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +sync_slave_with_master;
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +connection slave;
```suggestion
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +--sync_slave_with_master
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +--sync_slave_with_master
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +--sync_slave_with_master
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +sync_slave_with_master;
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +connection slave;
```suggestion
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +sync_slave_with_master;
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +connection slave;
```suggestion
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +sync_slave_with_master;
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +connection slave;
```suggestion
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +sync_slave_with_master;
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +connection slave;
```suggestion
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +sync_slave_with_master;
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +connection slave;
```suggestion
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +sync_slave_with_master;
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +connection slave;
```suggestion
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +sync_slave_with_master;
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +connection slave;
```suggestion
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +sync_slave_with_master;
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +--connection slave
```suggestion
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +--sync_slave_with_master
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +--sync_slave_with_master
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers.test
> +sync_slave_with_master;
rpl_end.inc will sync
```suggestion
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers_sbr.test
> +--sync_slave_with_master
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers_sbr.test
> +CALL mtr.add_suppression("impossible to write to binary log since statement is in row format and BINLOG_FORMAT = STATEMENT");
Didn't add_suppression on master replicate to slave too? (the texts are different too, the shorter one can be used)

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_row_triggers_sbr.test
> +--sync_slave_with_master
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_sql_log_bin_triggers.test
> +source include/have_binlog_format_row.inc;
Swap these two lines, cheap checks before expensive setups

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_sql_log_bin_triggers.test
> +sync_slave_with_master;
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_sql_log_bin_triggers.test
> +sync_slave_with_master;
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_sql_log_bin_triggers.test
> +sync_slave_with_master;
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_sql_log_bin_triggers.test
> +sync_slave_with_master;
```suggestion
--source include/sync_slave_sql_with_master.inc
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on sql/log_event.cc
> +      m_distinct_key_spare_buf(NULL),
```suggestion
      m_distinct_key_spare_buf(nullptr),
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on sql/log_event.cc
> +      master_had_triggers(0) {
:(
```suggestion
      master_had_triggers(false) {
```
or just use field initializers for both added fields

2019-02-01 07:57 UTC, laurynas-biveinis commented on sql/log_event.cc
> +      m_distinct_key_spare_buf(NULL),
Yeah, field initializers

2019-02-01 07:57 UTC, laurynas-biveinis commented on sql/log_event.cc
> +    (*lex->first_not_own_table()->prev_global) = NULL;
```suggestion
    (*lex->first_not_own_table()->prev_global) = nullptr;
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on sql/log_event.cc
> +  lex->query_tables = NULL;
```suggestion
  lex->query_tables = nullptr;
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on sql/log_event.cc
> +      DBUG_ASSERT(lex->query_tables == NULL);
```suggestion
      DBUG_ASSERT(lex->query_tables == nullptr);
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on sql/log_event.cc
> +      uint8 new_trg_event_map = get_trg_event_map();
```suggestion
      const auto new_trg_event_map = get_trg_event_map();
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on sql/log_event.cc
> +      LEX *lex = thd->lex;
```suggestion
      auto *lex = thd->lex;
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on sql/log_event.cc
> +      ("m_table: 0x%lx, m_table_id: %llu%s", (ulong)m_table, m_table_id.id(),
Printing pointer as pointer and not as 0x%lx was good already

```suggestion
      ("m_table: %p, m_table_id: %llu%s", m_table, m_table_id.id(),
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on sql/log_event.cc
> +  table_list->master_had_triggers = ((m_flags & TM_BIT_HAS_TRIGGERS_F) ? 1 : 0);
```suggestion
  table_list->master_had_triggers = m_flags & TM_BIT_HAS_TRIGGERS_F;
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on sql/log_event.h
> +  uint8 get_trg_event_map();
```suggestion
  uint8 get_trg_event_map() override;
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on sql/log_event.h
> +  uint8 get_trg_event_map();
```suggestion
  uint8 get_trg_event_map() override;
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on sql/log_event.h
> +  uint8 get_trg_event_map();
```suggestion
  uint8 get_trg_event_map() override;
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on sql/sp_instr.cc
> +    for (TABLE_LIST *tables = m_lex->query_tables; tables;
```suggestion
    for (auto *tables = m_lex->query_tables; tables;
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on sql/trigger.cc
> +  bool disable_binlog = !thd->variables.sql_log_bin_triggers;
```suggestion
  const auto disable_binlog = !thd->variables.sql_log_bin_triggers;
```

2019-02-01 07:57 UTC, laurynas-biveinis commented on mysql-test/r/mysqld--help-notwin.result
> +example ON
Should not be here, should it?

2019-02-01 14:34 UTC, inikep commented
PR is ready for a 2nd review. All comments except `auto` are addressed. I also updated `binlog_nogtid.binlog_persist_variables` and `binlog_nogtid.binlog_persist_only_variables` MTR tests.

2019-02-04 12:14 UTC, percona-ysorokin approved these changes
LGTM
(minor c++11 style comments)

2019-02-04 12:14 UTC, percona-ysorokin commented on sql/log_event.h
> +  virtual uint8 get_trg_event_map() = 0;
```suggestion
  virtual uint8 get_trg_event_map() const noexcept = 0;
```

2019-02-04 12:14 UTC, percona-ysorokin commented on sql/log_event.h
> +  uint8 get_trg_event_map() override;
```suggestion
  uint8 get_trg_event_map() const noexcept override;
```

2019-02-04 12:14 UTC, percona-ysorokin commented on sql/log_event.h
> +  uint8 get_trg_event_map() override;
```suggestion
  uint8 get_trg_event_map() const noexcept override;
```

2019-02-04 12:14 UTC, percona-ysorokin commented on sql/log_event.h
> +  uint8 get_trg_event_map() override;
```suggestion
  uint8 get_trg_event_map() const noexcept override;
```

2019-02-04 12:14 UTC, percona-ysorokin commented on sql/table.cc
> +void TABLE::set_pos_in_table_list(TABLE_LIST *table_list) {
```suggestion
void TABLE::set_pos_in_table_list(TABLE_LIST *table_list) noexcept {
```

2019-02-04 12:14 UTC, percona-ysorokin commented on sql/table.h
> +  void set_pos_in_table_list(TABLE_LIST *table_list);
```suggestion
  void set_pos_in_table_list(TABLE_LIST *table_list) noexcept;
```

2019-02-07 04:21 UTC, hermanlee approved these changes

2019-03-01 14:13 UTC, inikep commented
Conflicts were resolved and the commit was rebased.

2019-03-06 12:52 UTC, inikep commented
The commit was rebased and conflicts were solved.

2019-03-08 17:29 UTC, closed without merging