WIP FB8-84: Add global variable `max_nonsuper_connections`
facebook/mysql-5.6 pull request #950
Opened 2019-02-05 13:19 UTC by inikep

JIRA: https://jira.percona.com/browse/FB8-84

Reference Patch: https://github.com/facebook/mysql-5.6/commit/478fa2a

---------- https://github.com/facebook/mysql-5.6/commit/478fa2a ----------

Add global variable `max_nonsuper_connections`

Summary:
The new global variable `max_nonsuper_connections` will enforce the limit for
the sum of all non-admin connections. This will be useful to limit regular user
connections while still allow super users to connect to server.

fbshipit-source-id: 7ffb140

2019-02-06 07:16 UTC, laurynas-biveinis requested changes

2019-02-06 07:16 UTC, laurynas-biveinis commented on mysql-test/t/max_nonsuper_connections.test
> +create user test_user@localhost;
--source include/count_sessions.inc

2019-02-06 07:16 UTC, laurynas-biveinis commented on mysql-test/t/max_nonsuper_connections.test
> +}
--source include/wait_until_count_sessions.inc

2019-02-06 10:08 UTC, inikep commented
PR was updated and it is ready for 2nd review.

2019-02-06 10:20 UTC, percona-ysorokin requested changes

2019-02-06 10:20 UTC, percona-ysorokin commented on sql/mysqld.cc
> +ulong max_nonsuper_connections, nonsuper_connections = 0;
```suggestion
ulong max_nonsuper_connections = 0, nonsuper_connections = 0;
```

2019-02-06 10:20 UTC, percona-ysorokin commented on sql/system_variables.h
> +  ulong max_nonsuper_connections;
Is this really necessary? `max_nonsuper_connections` is GLOBAL var.

2019-02-06 11:24 UTC, inikep commented
PR was updated according to comments.

2019-02-06 12:02 UTC, percona-ysorokin approved these changes
LGTM

2019-02-07 16:38 UTC, hermanlee approved these changes

2019-03-06 13:09 UTC, inikep commented
This commit was rebased. Because of conflicts I removed changes in `mysql-test/t/all_persisted_variables.test`. This test has to be modified at `let $total_persistent_vars=XXX;` (+1 increase) and it should be re-recorded.

2019-03-12 14:09 UTC, closed without merging