WIP FB8-103: Heartbeat event should carry the latest master timestamp
facebook/mysql-5.6 pull request #951
Opened 2019-02-05 18:35 UTC by dutow

Jira issue: https://jira.percona.com/browse/FB8-103

Reference patch: https://github.com/facebook/mysql-5.6/commit/eb9a3db
Reference patch: https://github.com/facebook/mysql-5.6/commit/5803e4f
Reference patch: https://github.com/facebook/mysql-5.6/commit/746c217

Compared to the 5.6 patch:
* fixed the rpl_heartbeat_timestamp testcase, which resulted in the test executor killing all servers because of a connection drop
* split the rpl_heartbeat_zero_timestamp test into two

---------- https://github.com/facebook/mysql-5.6/commit/eb9a3db  ----------

Summary:
Heartbeat events should carry the now() timestamp from the master and
the last_master_timstamp from the slave. In other words, HB should always carry
the lastet master timestamp. This will help services connected to slaves know if
they are lagging even when no real events are flowing in the system.

Also, for this to work last_master_timestamp should be updated whenever a HB
event is received.

---------- https://github.com/facebook/mysql-5.6/commit/746c217 ----------

Summary:
Let master only send HB timestamp while waiting for new trx, this will fix the SBM being inaccurate when the slave is stopped and trying to catchup from the master.

2019-02-06 07:00 UTC, laurynas-biveinis requested changes
I don't like timing-dependant MTR style in this patch but not sure how to rewrite it without spending much effort neither (perhaps sync by waiting until the desired number of heartbeats have happened).

2019-02-06 07:00 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/include/rpl_heartbeat_zero_timestamp_input.inc
> +  eval drop database if exists test$i;
Redundant

2019-02-06 07:00 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/include/rpl_heartbeat_zero_timestamp_input.inc
> +  eval drop table if exists t$i;
Doubly redundant

2019-02-06 07:00 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_create_drop_temp_table.cnf
> +log-slave-updates
Default in 8.0. The cnf file should only set SERVER_MYPORT_3

2019-02-06 07:00 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_heartbeat_timestamp.cnf
> +[mysqld.1]
Default in 8.0. The cnf file should only set SERVER_MYPORT_3

2019-02-06 07:00 UTC, laurynas-biveinis commented on mysql-test/suite/rpl_gtid/t/rpl_heartbeat_zero_timestamp_mts.test
> +--disable_warnings
Why?

2019-02-06 07:00 UTC, laurynas-biveinis commented on mysql-test/suite/rpl_gtid/t/rpl_heartbeat_zero_timestamp_mts.test
> +SET GLOBAL DEBUG="+d, send_zero_hb_event";
--source include/have_debug.inc at the top?

2019-02-06 07:00 UTC, laurynas-biveinis commented on mysql-test/suite/rpl_gtid/t/rpl_heartbeat_zero_timestamp_nomts.test
> +################################################################################
Same comments as for MTS one.
The testcase looks copy-pasted, consider making an include file

2019-02-06 12:00 UTC, percona-ysorokin commented on sql/rpl_binlog_sender.cc
> +      bool time_for_hb_event =
```suggestion
#ifdef DBUG_OFF
const
#endif
bool time_for_hb_event = ...
```

2019-02-06 12:00 UTC, percona-ysorokin commented on sql/rpl_binlog_sender.cc
> +    if (!ts) ts = time(0);
```suggestion
    if (ts == 0) ts = time(nullptr);
```

2019-02-07 13:30 UTC, dutow commented on mysql-test/suite/rpl/include/rpl_heartbeat_zero_timestamp_input.inc
> +  eval drop database if exists test$i;
This part isn't redundant: the testcase first creates a few small tables, then drop them, and creates a few large.

2019-02-07 14:41 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/include/rpl_heartbeat_zero_timestamp_input.inc
> +  eval drop database if exists test$i;
I see, in which case I'd rewrite this with drops after use

2019-02-08 07:22 UTC, dutow commented
Updated.

2019-02-08 09:18 UTC, percona-ysorokin approved these changes
LGTM

2019-02-12 21:21 UTC, hermanlee requested changes
I'm seeing an error running the rpl.rpl_heartbeat_timestamp test. It results in:

```
There is no group named 'mysqld.3' that can be used to resolve 'port' at /home/herman/rocks-mysql/8.0/mysql-test/mysql-test-run.pl line 4359. 
```

I've added the missing lines to mysql-test/suite/rpl/t/rpl_heartbeat_timestamp.cnf:

```
[mysqld.1]
log-slave-updates
[mysqld.2]
log-slave-updates
[mysqld.3]
log-slave-updates
```

and the test looks to start running properly again.

2019-02-27 21:58 UTC, hermanlee approved these changes

2019-02-28 01:30 UTC, closed without merging