WIP FB8-80: Display row information in processlist for rbr threads
facebook/mysql-5.6 pull request #953
Opened 2019-02-07 15:00 UTC by inikep

Jira ticket: https://jira.percona.com/browse/FB8-80

Reference Patch: https://github.com/facebook/mysql-5.6/commit/564824a

Summary: Set row_query using the fields unpacked from the row event. Use row_query in show processlist.

Test Plan: mtr

Reviewers: tianx

Originally Reviewed By: tianx

Subscribers: webscalesql-eng, ebergen

2019-02-08 11:21 UTC, percona-ysorokin approved these changes
LGTM
(just minor stylistic comments)

2019-02-08 11:21 UTC, percona-ysorokin commented on sql/rpl_record.cc
> +  static const size_t max_field_len = 100;
```suggestion
  static constexpr size_t max_field_len = 100;
```

2019-02-08 11:21 UTC, percona-ysorokin commented on sql/rpl_record.cc
> +static void insert_row_fields(std::string *row_query, TABLE *table) {
There is no checking for `row_query != nullptr`.
Pass inout parameters by reference
```suggestion
static void insert_row_fields(std::string &row_query, TABLE *table) {
```

2019-02-08 11:21 UTC, percona-ysorokin commented on sql/rpl_record.cc
> +                                 std::string *row_query) {
pass by reference

2019-02-08 11:21 UTC, percona-ysorokin commented on sql/rpl_record.cc
> +                std::string *row_query) {
pass by reference

2019-02-08 11:21 UTC, percona-ysorokin commented on sql/rpl_record.h
> +                std::string *row_query = nullptr);
pass by reference, no default param

2019-02-08 11:21 UTC, percona-ysorokin commented on sql/sql_show.cc
> +      if (inspect_thd->row_query.size()) {
```suggestion
      if (!inspect_thd->row_query.empty()) {
```

2019-02-08 11:21 UTC, percona-ysorokin commented on sql/sql_show.cc
> +      if (inspect_thd->row_query.size()) {
```suggestion
      if (!inspect_thd->row_query.empty()) {
```

2019-02-22 18:58 UTC, hermanlee requested changes
The changes look good, but the follow tests look to be failing:

rpl.rpl_multi_source_row_stages
rpl.rpl_invalid_mem_access_with_rows_query_log_event

2019-03-01 14:53 UTC, inikep commented
Failing tests were fixed and the commit was rebased.

2019-03-06 19:28 UTC, hermanlee approved these changes

2019-03-11 16:55 UTC, closed without merging