WIP FB8-136: Wait on disk full for binlog cache
facebook/mysql-5.6 pull request #964
Opened 2019-02-18 16:39 UTC by inikep

Jira issue: https://jira.percona.com/browse/FB8-136

Reference Patch: https://github.com/facebook/mysql-5.6/commit/6168b96

Summary: This branch unifies behavior when server faces disk full issue. Previously a server was waiting until disk is free for direct binlog writes but reported an error to a client if it hits the issue while writing to binlog cache which is written to a separate folder and might be mounted to a different partition.

Originally Reviewed By: abhinav04sharma

fbshipit-source-id: 3889417

2019-02-25 12:01 UTC, laurynas-biveinis requested changes

2019-02-25 12:01 UTC, laurynas-biveinis commented on mysql-test/suite/binlog/t/binlog_cache_disk_full-master.opt
> +--log-error=$MYSQLTEST_VARDIR/tmp/binlog_cache_disk_full.err
Consider replacing this with server restart in the testcase with the error log path, restart in the end, deleting this error log.
The testcase tries to fix --repeat with exec truncate, but this approach is more portable to e.g. Windows, which may matter if this patch is ever upstreamed

2019-02-25 12:03 UTC, percona-ysorokin requested changes

2019-02-25 12:03 UTC, percona-ysorokin commented on mysql-test/suite/binlog/t/binlog_cache_disk_full.test
> +insert into t1 values(md5(1));
Consistent upper/lower case for SQL statements.

2019-02-25 12:03 UTC, percona-ysorokin commented on mysql-test/suite/binlog/t/binlog_cache_disk_full.test
> +--exec truncate -s 0 $error_log
I would rather go with restarting MySQL Server via `--source include/restart_mysqld.inc`
with `--let $restart_parameters= restart: --binlog_cache_size=4096 --log-error=$error_log`.
Then doing all the logic and asserts.
After that restarting it again with `--let $restart_parameters=` and deleting the log file with regular `--remove_file $error_log`.

2019-02-25 12:03 UTC, percona-ysorokin commented on mysql-test/suite/binlog/t/binlog_cache_disk_full-master.opt
> +--binlog_cache_size=4096
This file is not needed (see below).

2019-02-27 12:12 UTC, inikep commented
PR was improved to use `$assert_only_after` with `assert_grep.inc` that allows `--repeat` to work fine without restarting a server and deleting logs.

2019-02-27 14:14 UTC, percona-ysorokin approved these changes
LGTM

2019-03-04 10:31 UTC, inikep commented
The commit was rebased.

2019-03-06 21:50 UTC, hermanlee approved these changes

2019-03-06 21:50 UTC, closed without merging