WIP FB8-131: Option to shutdown master if semi-sync is being switched off while there are active un-acked trxns
facebook/mysql-5.6 pull request #966
Opened 2019-02-21 12:36 UTC by inikep

Jira issue: https://jira.percona.com/browse/FB8-131

Reference Patch: https://github.com/facebook/mysql-5.6/commit/2d47615
Reference Patch: https://github.com/facebook/mysql-5.6/commit/d1ea741
Reference Patch: https://github.com/facebook/mysql-5.6/commit/f5085f4
Reference Patch: https://github.com/facebook/mysql-5.6/commit/9204c65

---------- https://github.com/facebook/mysql-5.6/commit/2d47615 ----------

Option to shutdown master if semi-sync is being switched off while there are active un-acked trxns

Summary:
Semi-sync master can be switched off manually or because of a timeout while
waiting for an ack.

This change introduces a new variable rpl_semi_sync_master_crash_if_active_trxs
which when set to true will cause the master to shutdown (after printing an
error msg) if semi-sync is being switched off while there are active un-acked
transactions. This prevents any un-acked trx from committing on the
master.

Originally Reviewed By: hermanlee

fbshipit-source-id: https://github.com/facebook/mysql-5.6/commit/c378441cb197f3a2759b8a81814ec0905caf0ed8

---------- https://github.com/facebook/mysql-5.6/commit/d1ea741 ----------

Fix test flakiness in rpl.rpl_semi_sync-master_crash_if_active_trxs

Summary:
The test would sometimes fail if the slave's retry count is exhausted
before the master comes up. Set the slave to retry forever instead.

Squash with D5841339

Originally Reviewed By: abhinav04sharma

fbshipit-source-id: https://github.com/facebook/mysql-5.6/commit/c12f822a4df784d95fb99b308d03c8feb4309327

---------- https://github.com/facebook/mysql-5.6/commit/f5085f4 ----------

Use master_retry_count to fix rpl.rpl_semi_sync_master_crash_if_active_trxs

Summary:
The proper variable to adjust is master_retry_count, not
master_connect_retry.

Squash with D5841339

Originally Reviewed By: abhinav04sharma

fbshipit-source-id: https://github.com/facebook/mysql-5.6/commit/6938715f85058fec3b6b41ddb95ac800e9ff925c

---------- https://github.com/facebook/mysql-5.6/commit/9204c65 ----------

Delete pid file when crashing after timeout with unacked trx

Summary:
If rpl_semi_sync_master_crash_if_active_trxs = true, the server crashes after a
timeout if there are any active unacked transactions. mysqld_safe expects the
pid file to be deleted if the expectation is to not bring the intance back up
again. This change deletes the pid file before crashing on this condition.

Squash with D5841339

Originally Reviewed By: Tema

fbshipit-source-id: https://github.com/facebook/mysql-5.6/commit/a94df242f3950393b257060cf15ea3f2dd651152

2019-02-25 09:31 UTC, laurynas-biveinis requested changes

2019-02-25 09:31 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_semi_sync_master_crash_if_active_trxs.test
> +source include/have_debug.inc;
Swap

2019-02-25 09:31 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_semi_sync_master_crash_if_active_trxs.test
> +connection slave;
Redundant

2019-02-25 09:31 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_semi_sync_master_crash_if_active_trxs.test
> +connection slave;
Redundant

2019-02-25 09:31 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_semi_sync_master_crash_if_active_trxs.test
> +--source include/sync_slave_sql_with_master.inc
Redundant

2019-02-25 09:31 UTC, laurynas-biveinis commented on plugin/semisync/semisync_master_plugin.cc
> +                         NULL, NULL, 0);
nullptr, nullptr, false?

2019-02-25 12:39 UTC, inikep commented
PR was updated according to comments

2019-02-25 15:45 UTC, percona-ysorokin requested changes

2019-02-25 15:45 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_semi_sync_master_crash_if_active_trxs.test
> +connection master;
```suggestion
--source include/rpl_connection_master.inc
```

2019-02-25 15:45 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_semi_sync_master_crash_if_active_trxs.test
> +connection master;
```suggestion
--source include/rpl_connection_master.inc
```

2019-02-25 15:45 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_semi_sync_master_crash_if_active_trxs.test
> +connection slave;
```suggestion
--source include/rpl_connection_slave.inc
```

2019-02-25 15:45 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_semi_sync_master_crash_if_active_trxs.test
> +connection master;
```suggestion
--source include/rpl_connection_master.inc
```

2019-02-25 15:45 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_semi_sync_master_crash_if_active_trxs.test
> +connection master;
```suggestion
--source include/rpl_connection_master.inc
```

2019-02-25 15:45 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_semi_sync_master_crash_if_active_trxs.test
> +connection slave;
```suggestion
--source include/rpl_connection_slave.inc
```

2019-02-25 15:45 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_semi_sync_master_crash_if_active_trxs.test
> +connection master1;
```suggestion
--source include/rpl_connection_master1.inc
```

2019-02-25 15:45 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_semi_sync_master_crash_if_active_trxs.test
> +connection master;
```suggestion
--source include/rpl_connection_master.inc
```

2019-02-25 15:45 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_semi_sync_master_crash_if_active_trxs.test
> +connection slave;
```suggestion
--source include/rpl_connection_slave.inc
```

2019-02-25 15:45 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_semi_sync_master_crash_if_active_trxs.test
> +connection master;
```suggestion
--source include/rpl_connection_master.inc
```

2019-02-25 15:45 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_semi_sync_master_crash_if_active_trxs.test
> +connection master;
```suggestion
--source include/rpl_connection_master.inc
```

2019-02-25 15:45 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_semi_sync_master_crash_if_active_trxs.test
> +connection slave;
```suggestion
--source include/rpl_connection_slave.inc
```

2019-02-25 15:45 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_semi_sync_master_crash_if_active_trxs.test
> +connection master;
```suggestion
--source include/rpl_connection_master.inc
```

2019-02-25 15:45 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_semi_sync_master_crash_if_active_trxs.test
> +connection master;
```suggestion
--source include/rpl_connection_master.inc
```

2019-02-26 10:51 UTC, inikep commented
PR was updated

2019-02-26 14:09 UTC, percona-ysorokin approved these changes
LGTM with `connection master1` addressed

2019-02-26 14:09 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_semi_sync_master_crash_if_active_trxs.test
> +connection master1;
Not fixed

2019-03-07 19:18 UTC, lth approved these changes

2019-03-08 18:12 UTC, closed without merging