WIP FB8-167: Add variable to force range plans if force index is used
facebook/mysql-5.6 pull request #967
Opened 2019-02-21 15:11 UTC by inikep

Jira ticket: https://jira.percona.com/browse/FB8-167

Reference Patch: https://github.com/facebook/mysql-5.6/commit/b01ff6a

Summary:
Currently, when force index is used, full table scans are highly penalized, but it is still possible to do a full index scan which is expensive. In many cases, we only use force index when we know there is better way to traverse the index, and not necessarily because we want a full index scan.

To address these cases, add a session variable called optimizer_force_index_for_range, which when turned on, will try to search for a 'range' plan before falling back to an index plan.

Originally Reviewed By: hermanlee

fbshipit-source-id: 4a4641b

2019-02-25 15:51 UTC, percona-ysorokin commented on mysql-test/t/optimizer_force_index_for_range.test
> +set @orig_optimizer_force_index_for_range = @@optimizer_force_index_for_range;
no need to save/restore a session variable

2019-02-25 15:56 UTC, percona-ysorokin requested changes

2019-02-25 15:56 UTC, percona-ysorokin commented on mysql-test/t/optimizer_force_index_for_range.test
> +set optimizer_force_index_for_range = @orig_optimizer_force_index_for_range;
no need to save/restore a session variable

2019-02-25 15:56 UTC, percona-ysorokin commented on sql/sys_vars.cc
> +    SESSION_VAR(optimizer_force_index_for_range), CMD_LINE(OPT_ARG),
Consider `HINT_UPDATEABLE` here.

2019-02-26 11:51 UTC, inikep commented
PR was updated according to comments.

2019-02-26 15:46 UTC, percona-ysorokin approved these changes
LGTM with saving/restoring session var issue addressed

2019-02-26 15:46 UTC, percona-ysorokin commented on mysql-test/t/optimizer_force_index_for_range.test
> +SET @session_optimizer_force_index_for_range = @@session.optimizer_force_index_for_range;
not fixed
no need to save/restore session variables

2019-02-26 15:46 UTC, percona-ysorokin commented on mysql-test/t/optimizer_force_index_for_range.test
> +SET @@session.optimizer_force_index_for_range = @session_optimizer_force_index_for_range;
not fixed
no need to save/restore session variables

2019-03-08 08:44 UTC, inikep commented
Because of conflicts I removed changes in mysql-test/t/all_persisted_variables.test. This test has to be modified at let $total_persistent_vars=XXX; (+1 increase) and it should be re-recorded.

2019-03-11 17:24 UTC, closed without merging