WIP FB8-187: New variable binlog_rows_event_max_rows to control the number of rows in a single rows event
facebook/mysql-5.6 pull request #974
Opened 2019-02-27 14:32 UTC by inikep

Jira issue: https://jira.percona.com/browse/FB8-187

Reference Patch: https://github.com/facebook/mysql-5.6/commit/dfe6746cdfd

Summary:
Number of rows in a single event can be indirectly controlled with
binlog_rows_event_max_size. This new variable will give more direct control to
the user.

Originally Reviewed By: anirbanr-fb

fbshipit-source-id: bfb8492

2019-02-28 09:59 UTC, percona-ysorokin requested changes

2019-02-28 09:59 UTC, percona-ysorokin commented on mysql-test/suite/binlog/t/binlog_rows_event_max_rows.test
> +--source include/sync_slave_sql_with_master.inc
redundant
```suggestion
```

2019-02-28 09:59 UTC, percona-ysorokin commented on mysql-test/suite/binlog/t/binlog_rows_event_max_rows.test
> +exec $MYSQL_BINLOG -v -v $MYSQLD_DATADIR/master-bin.0* | grep "Write_rows" | wc -l;
Does this run OK with `--repeat=2`?

2019-02-28 09:59 UTC, percona-ysorokin commented on sql/sys_vars.cc
> +    NO_MUTEX_GUARD, NOT_IN_BINLOG, ON_CHECK(0), ON_UPDATE(0));
```suggestion
    NO_MUTEX_GUARD, NOT_IN_BINLOG, ON_CHECK(nullptr), ON_UPDATE(nullptr));
```

2019-02-28 09:59 UTC, percona-ysorokin commented on mysql-test/suite/binlog/t/binlog_rows_event_max_rows.test
> +set @@global.binlog_rows_event_max_rows= default;
Save and restore the value of `binlog_rows_event_max_rows` rather than rely on `DEFAULT`

2019-02-28 09:59 UTC, percona-ysorokin commented on mysql-test/suite/binlog/t/binlog_rows_event_max_rows.test
> +source include/master-slave.inc;
Is `master-slave.inc` is really needed here?

2019-03-01 10:40 UTC, inikep commented on mysql-test/suite/binlog/t/binlog_rows_event_max_rows.test
> +exec $MYSQL_BINLOG -v -v $MYSQLD_DATADIR/master-bin.0* | grep "Write_rows" | wc -l;
no

2019-03-01 10:53 UTC, inikep commented
All comments were addressed, fixed `--repeat=2`, rebased to trunk.

2019-03-04 10:02 UTC, percona-ysorokin approved these changes
LGTM

2019-03-22 00:12 UTC, hermanlee approved these changes

2019-03-25 20:58 UTC, closed without merging