WIP FB8-104: enabling subsecond lock_wait_timeout
facebook/mysql-5.6 pull request #980
Opened 2019-03-05 12:33 UTC by dutow

For a first review, I only added the code changes to this pull request for two reasons:
* a full test is still running, and I'll have to check the results (I do see a few non output only failures because timeouts, so looks like I missed some nsec-sec conversion in this diff - I'll fix that and update). And checking output changes / rerecording will take time.
* compared to the 5.6 patch, the code change for 8.0 is huge, and affects the service api - reviewing only the code changes is probably a good idea

Jira ticket: https://jira.percona.com/browse/FB8-104

Reference commit: https://github.com/facebook/mysql-5.6/commit/c21adb7

-------- c21adb7 --------

Currently lock_wait_timeout is an integer type variable which only have
seconds resolution. We would want to extend the variable to double/decimal
type, so it can have milliseconds or microseconds resolution, such as
lock_wait_timeout = 1.23. The integral part should still mean seconds to
keep backward compatibility.

The range of valid values expanded to [ 0 .. 604800 ] to allow timeouts below
1 second; such as lock_wait_timeout = 0.005.  Values that are too small
will effectively mean not waiting for locks.

This update also changes the output of lock_wait_timeout to be decimal;
note the extra .000000 appended to the seconds.

    SELECT @global.lock_wait_timeout;
    @global.lock_wait_timeout
    604800.000000

2019-03-05 15:32 UTC, percona-ysorokin requested changes

2019-03-05 15:32 UTC, percona-ysorokin commented on sql/auth/sql_auth_cache.cc
> +static const ulong ACL_CACHE_LOCK_TIMEOUT_NSEC =
`ulong` is not guaranteed to be 64-bit, and therefore may be truncated here as `ACL_CACHE_LOCK_TIMEOUT * 1000000000ULL >2^32`
```suggestion
static constexpr ulonglong ACL_CACHE_LOCK_TIMEOUT_NSEC =
```

2019-03-05 15:32 UTC, percona-ysorokin commented on sql/sys_vars.cc
> +    CMD_LINE(REQUIRED_ARG), VALID_RANGE(0, LONG_TIMEOUT), DEFAULT(LONG_TIMEOUT),
Is `0` a valid value now on purpose?

2019-03-05 17:43 UTC, dutow commented on sql/sys_vars.cc
> +    CMD_LINE(REQUIRED_ARG), VALID_RANGE(0, LONG_TIMEOUT), DEFAULT(LONG_TIMEOUT),
Yes, to allow values below 1 second.

2019-03-05 18:26 UTC, dutow commented on sql/auth/sql_auth_cache.cc
> +static const ulong ACL_CACHE_LOCK_TIMEOUT_NSEC =
Thanks, this was one of the typos. I found another when rereading my changes, looks like there aren't any timeout errors so far with these changes.

Updated, and I'll do another update tomorrow with the test changes.

2019-03-06 12:19 UTC, dutow commented
Updated with changed tests.

2019-03-06 13:44 UTC, percona-ysorokin approved these changes
LGTM

2019-03-12 12:05 UTC, hermanlee requested changes
I'm seeing a number of test failures due to loading of locking_service.so.

CURRENT_TEST: main.locking_service
mysqltest: At line 34: Query 'CREATE FUNCTION service_get_read_locks  RETURNS INT SONAME "$LOCKING_SERVICE"' failed.
ERROR 1126 (HY000): Can't open shared library 'locking_service.so' (errno: 0 /data/users/herman/rocks-mysql/8.0/_build-8.0-Debug/plugin_output_directory/locking_
service.so: undefined symbol: _Z29acquire_lo)

I think some of the plugins and gunit tests need to change acquire_locking_service_locks to acquire_locking_service_locks_nsec?

2019-03-12 12:05 UTC, hermanlee commented on components/mysql_server/mysql_backup_lock.h
> +  This program is free software; you can redistribute it and/or modify
Could this indent change be reverted and the original indent spacing be preserved?

2019-03-21 22:39 UTC, hermanlee approved these changes

2019-04-01 16:19 UTC, closed without merging