WIP FB8-132: NUMA support
facebook/mysql-5.6 pull request #987
Opened 2019-03-18 09:03 UTC by dutow

Jira ticket: https://jira.percona.com/browse/FB8-132

Reference commit: https://github.com/facebook/mysql-5.6/commit/e50c754879828c1d0b4f40cc13475ec7adea9afc
Reference commit: https://github.com/facebook/mysql-5.6/commit/286e975

-------- e50c754 --------

WebScaleSQL Feature: NUMA Support

Credits for research and implementation: Jeremy Cole and Davi Arnaut

This patch provides startup options:
* flush-caches: Flush and purge buffers/caches
* numa-interleave: Run mysqld with its memory interleaved on all CPUs

It also provides a config option:
* innodb_buffer_pool_populate: pre-allocation of buffer pool
memory at start up:
  -- Use MAP_POPULATE if supported (Linux 2.6.23 and higher)
  -- Forced pre-allocation using memset

-------- 286e975 --------

Automation will pass in the right value to this option if
it needs to bind mysqld to a particular socket. That will happen
via systemd scripts.

This is only adding the capability on the mysqld_safe side to be able to
pass in numactl to the server. The turning on of this feature will need more
testing and slow roll, and that will happen in different diffs on the ops repo.

2019-03-18 10:21 UTC, percona-ysorokin approved these changes
LGTM

2019-03-18 15:20 UTC, dutow commented
Note: I didn't do much testing - I have no numa capable hardware.

2019-03-19 06:45 UTC, laurynas-biveinis requested changes

2019-03-19 06:45 UTC, laurynas-biveinis commented on scripts/mysqld_safe.sh
> +numa_interleave=0
Isn't mysqld_safe.sh numa_interleave option redundant due to 5.7 core server --innodb-numa-interleave?

2019-03-19 06:45 UTC, laurynas-biveinis commented on storage/innobase/handler/ha_innodb.cc
> +    NULL, NULL, FALSE);
```suggestion
    nullptr, nullptr, false);
```

2019-03-19 06:45 UTC, laurynas-biveinis commented on storage/innobase/os/os0proc.cc
> +/****************************************************************/ /**
New style header comment please

2019-03-19 06:45 UTC, laurynas-biveinis commented on storage/innobase/os/os0proc.cc
> + @return	TRUE if the OS release is equal to, or later than release. */
```suggestion
 @return	true if the OS release is equal to, or later than release. */
```

2019-03-19 06:45 UTC, laurynas-biveinis commented on storage/innobase/os/os0proc.cc
> +  return (FALSE);
```suggestion
  return (false);
```

2019-03-19 06:45 UTC, laurynas-biveinis commented on storage/innobase/os/os0proc.cc
> +    fprintf(stderr,
ib::warn()

2019-03-22 17:03 UTC, hermanlee commented
Can this be rebased onto the latest 8.0.13? Thanks!

2019-04-15 20:25 UTC, hermanlee approved these changes

2019-04-15 20:25 UTC, hermanlee commented on storage/innobase/srv/srv0start.cc
> +  err = buf_pool_init(srv_buf_pool_size, srv_buf_pool_populate,
I'll fix this, but populate and instances need to be swapped.

2019-05-09 22:10 UTC, closed without merging