WIP FB8-78: Add filesort_max_file_size option
facebook/mysql-5.6 pull request #993
Opened 2019-03-19 12:50 UTC by inikep

Jira issue: https://jira.percona.com/browse/FB8-78

Reference Patch: https://github.com/facebook/mysql-5.6/commit/11ef068

Summary:
Add the filesort_max_file_size variable setting which specifies the maximum number of bytes a filesort file can take. If it is exceeded, then the query fails.

This is very similar to the tmp_table_max_file_size variable.

Test Plan: main.max_filesort_size

Reviewers: jkedgar, gunnarku

Originally Reviewed By: gunnarku

Subscribers: webscalesql-eng

2019-03-20 09:25 UTC, laurynas-biveinis requested changes

2019-03-20 09:25 UTC, laurynas-biveinis commented on mysql-test/suite/sys_vars/t/filesort_max_file_size_basic.test
> +SET @start_session_value = @@session.filesort_max_file_size;
Redundant

2019-03-20 09:25 UTC, laurynas-biveinis commented on mysql-test/t/max_filesort_size.test
> +set @save_filesort_max_file_size = @@global.filesort_max_file_size;
--source include/count_sessions.inc

2019-03-20 09:25 UTC, laurynas-biveinis commented on mysql-test/t/max_filesort_size.test
> +set @@global.filesort_max_file_size = @save_filesort_max_file_size;
--source include/wait_until_count_sessions.inc

2019-03-22 10:50 UTC, inikep commented
PR was updated

2019-03-24 12:32 UTC, percona-ysorokin commented on mysql-test/t/max_filesort_size.test
> +connect (root,localhost,root,,test,$MASTER_MYPORT,$MASTER_MYSOCK);
Can be just
```suggestion
connect (root,localhost,root,,test);
```

2019-03-24 12:32 UTC, percona-ysorokin commented on mysql-test/t/max_filesort_size.test
> +connect (root,localhost,root,,test,$MASTER_MYPORT,$MASTER_MYSOCK);
Can be just
```suggestion
connect (root,localhost,root,,test);
```

2019-03-24 12:32 UTC, percona-ysorokin commented on sql/sys_vars.cc
> +    SESSION_VAR(filesort_max_file_size), CMD_LINE(REQUIRED_ARG),
May be `HINT_UPDATABLE`?

2019-03-25 11:01 UTC, inikep commented
PR updated according to comments.

2019-03-25 12:49 UTC, percona-ysorokin approved these changes
LGTM

2019-04-10 21:58 UTC, hermanlee requested changes

2019-04-10 21:58 UTC, hermanlee commented on share/errmsg-utf8.txt
> +ER_FILESORT_MAX_FILE_SIZE_EXCEEDED
Should replace  ER_PLACEHOLDER_50037 instead.

2019-04-12 13:19 UTC, inikep commented
PR was updated with `ER_FILESORT_MAX_FILE_SIZE_EXCEEDED` replacing `ER_PLACEHOLDER_50037`.

2019-05-10 08:20 UTC, inikep commented
Already merged at https://github.com/facebook/mysql-5.6/commit/cc088df2854093614bb26461b0a443c5eab995f2

2019-05-10 08:20 UTC, closed without merging