WIP FB8-106: Add more information to duplicate key error
facebook/mysql-5.6 pull request #998
Opened 2019-03-22 10:01 UTC by inikep

Jira issue: https://jira.percona.com/browse/FB8-106

Reference Patch: https://github.com/facebook/mysql-5.6/commit/2c7f717
Reference Patch: https://github.com/facebook/mysql-5.6/commit/f3a0ed0

Summary: The current error information for duplicate key lists the key value and key name.  In some scenarios this may not be sufficient.  Add a variable that, when enabled, includes the tableame for the key and the query text (or up to 512 bytes of it) into the error message.  The new variable, improved_dup_key_error, will change the output error message to contain this new information.

Originally Reviewed By: hermanlee

fbshipit-source-id: 1c0cf40

2019-03-24 13:14 UTC, percona-ysorokin requested changes

2019-03-24 13:14 UTC, percona-ysorokin commented on storage/innobase/handler/ha_innodb.h
> +  inline MY_ATTRIBUTE((warn_unused_result)) bool commit_try_rebuild(
No definition available  - so not inline
```suggestion
  MY_ATTRIBUTE((warn_unused_result)) bool commit_try_rebuild(
```

2019-03-24 13:14 UTC, percona-ysorokin commented on storage/innobase/handler/handler0alter.cc
> +inline MY_ATTRIBUTE((warn_unused_result)) bool ha_innobase::commit_try_rebuild(
```suggestion
MY_ATTRIBUTE((warn_unused_result)) bool ha_innobase::commit_try_rebuild(
```

2019-03-25 06:55 UTC, laurynas-biveinis requested changes

2019-03-25 06:55 UTC, laurynas-biveinis commented on sql/mysqld.cc
> +bool opt_improved_dup_key_error = 0;
```suggestion
bool opt_improved_dup_key_error = false;
```

2019-03-25 11:24 UTC, inikep commented
PR was updated according to comments.

2019-03-25 12:53 UTC, percona-ysorokin approved these changes
LGTM

2019-04-10 21:34 UTC, hermanlee approved these changes

2019-04-15 17:25 UTC, closed without merging